export const skillsLogos = [
    "devicon-javascript-plain",
    "devicon-python-plain-wordmark",
    "devicon-html5-plain-wordmark",
    "devicon-css3-plain-wordmark",
    "devicon-jquery-plain-wordmark",
    "devicon-nodejs-plain-wordmark",
    "devicon-react-original-wordmark",
    "devicon-django-plain",
    "devicon-express-original-wordmark",
    "devicon-mongodb-plain-wordmark",
    "devicon-postgresql-plain-wordmark",
    "devicon-bootstrap-plain-wordmark",
    "devicon-git-plain-wordmark",
    "devicon-github-plain-wordmark",
];